Repository pymc-devs/pymc4, pull requests merged in 2019-03, with the labels that each got.

#70 proposal PR to re-implement distributions API to match PyMC3
  .gitignore
  pymc4/random_variables/__init__.py
  pymc4/random_variables/continuous.py
  pymc4/random_variables/discrete.py
  pymc4/random_variables/mixture.py
  pymc4/random_variables/multivariate.py
  pymc4/random_variables/random_variable.py
  pymc4/tests/test_linear_regression.py
  pymc4/tests/test_random_variables.py
  pymc4/tests/test_template_context.py
Labels: discussion

#83 initial implementation of transforms
  pymc4/_template_contexts.py
  pymc4/random_variables/continuous.py
  pymc4/random_variables/discrete.py
  pymc4/random_variables/multivariate.py
  pymc4/random_variables/random_variable.py
  pymc4/tests/test_linear_regression.py
  pymc4/tests/test_random_variables.py
Labels: WIP

#86 Auto name RVs by parsing AST
  pymc4/_model.py
  pymc4/ast_compiler.py
  pymc4/random_variables/discrete.py
  pymc4/random_variables/random_variable.py
  pymc4/tests/test_autoname.py
  pymc4/tests/test_random_variables.py
  pymc4/tests/test_template_context.py
Labels: enhancement
